name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - uses: pre-commit/action@v3.0.1
      - uses: astral-sh/setup-uv@v8
      - run: uv pip install --system -r requirements-test.txt
      - run: pytest -v
